import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime

def generate_html_report(data):
    """
    Generates a HTML report from the backtest results.
    Accepts either a single result dict or a list of result dicts (for combined reports).
    """
    html_content = _get_head_template()
    html_content += "<body><div class='container'>"
    
    if isinstance(data, list):
        # Combined Report
        html_content += f"""
        <h1>Combined Portfolio Report</h1>
        <p>Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        """
        
        # Add Comparison Section
        html_content += _generate_comparison_section(data)
        
        # Add Individual Reports
        for i, res in enumerate(data):
            html_content += "<hr class='section-divider'>"
            html_content += f"<h1 id='port_{i}'>Portfolio: {res.get('name', f'Portfolio {i+1}')}</h1>"
            html_content += _generate_single_report_body(res, show_title=False)
            
    else:
        # Single Report
        html_content += f"<h1>Backtest Report: {data.get('name', 'Portfolio')}</h1>"
        html_content += f"<p>Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>"
        html_content += _generate_single_report_body(data, show_title=False)

    html_content += """
        <div style="margin-top: 50px; font-size: 0.8em; color: #777; text-align: center;">
            <p>Generated by Testfol Margin Stresser</p>
        </div>
    </div></body></html>
    """
    return html_content

def _generate_comparison_section(results_list):
    """Generates a comparison table and chart for multiple portfolios."""
    
    # 1. Comparison Table
    rows = []
    for res in results_list:
        stats = res.get("stats", {})
        series = res.get("port_series", pd.Series([0]))
        end_val = series.iloc[-1] if not series.empty else 0
        
        row = {
            "Portfolio": res.get("name", "Unknown"),
            "CAGR": stats.get("cagr", 0),
            "Vol": stats.get("vol", 0),
            "Max DD": stats.get("max_drawdown", 0),
            "Sharpe": stats.get("sharpe", 0),
            "End Value": end_val
        }
        rows.append(row)
        
    df_compare = pd.DataFrame(rows)
    
    # Format for HTML
    # We construct HTML table manually to avoid pandas styling issues or use to_html simply
    table_html = "<table class='styled-table'><thead><tr>"
    for col in df_compare.columns:
        table_html += f"<th>{col}</th>"
    table_html += "</tr></thead><tbody>"
    
    for _, row in df_compare.iterrows():
        table_html += "<tr>"
        table_html += f"<td><strong>{row['Portfolio']}</strong></td>"
        table_html += f"<td>{row['CAGR']:.2%}</td>"
        table_html += f"<td>{row['Vol']:.2%}</td>"
        table_html += f"<td>{row['Max DD']:.2%}</td>"
        table_html += f"<td>{row['Sharpe']:.2f}</td>"
        table_html += f"<td>${row['End Value']:,.2f}</td>"
        table_html += "</tr>"
    table_html += "</tbody></table>"
    
    # 2. Comparison Chart (Equity Curves)
    fig = go.Figure()
    for res in results_list:
        series = res.get("port_series")
        if series is not None and not series.empty:
            fig.add_trace(go.Scatter(
                x=series.index, y=series, mode='lines', name=res.get("name", "Portfolio")
            ))
            
    fig.update_layout(
        title="Portfolio Comparison (Value)",
        xaxis_title="Date",
        yaxis_title="Value ($)",
        template="plotly_white",
        height=400,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )
    chart_html = fig.to_html(full_html=False, include_plotlyjs='cdn')
    
    return f"""
    <h2>Comparison Summary</h2>
    <div class="table-container">{table_html}</div>
    <div class="chart-container">{chart_html}</div>
    """

def _generate_single_report_body(results, show_title=True):
    """
    Generates the body content for a single portfolio report.
    """
    html_out = ""
    
    # Extract Data
    port_series = results.get("port_series", pd.DataFrame())
    stats = results.get("stats", {})
    pl_by_year = results.get("pl_by_year", pd.DataFrame())
    
    if port_series.empty:
        return "<p>No Data Available</p>"

    # --- Generate Charts ---
    
    # 1. Equity Curve
    fig_equity = go.Figure()
    fig_equity.add_trace(go.Scatter(
        x=port_series.index, 
        y=port_series, 
        mode='lines', 
        name='Portfolio Value',
        line=dict(color='#00CC96', width=2)
    ))
    fig_equity.update_layout(
        title="Portfolio Performance",
        xaxis_title="Date",
        yaxis_title="Value ($)",
        template="plotly_white",
        height=400
    )
    html_equity = fig_equity.to_html(full_html=False, include_plotlyjs=False) # CDN loaded in head/comparison
    
    # 2. Drawdown
    rolling_max = port_series.cummax()
    drawdown = (port_series - rolling_max) / rolling_max
    
    fig_dd = go.Figure()
    fig_dd.add_trace(go.Scatter(
        x=port_series.index, 
        y=drawdown, 
        mode='lines', 
        name='Drawdown',
        line=dict(color='#EF553B', width=1),
        fill='tozeroy'
    ))
    fig_dd.update_layout(
        title="Drawdown",
        xaxis_title="Date",
        yaxis_title="Drawdown (%)",
        template="plotly_white",
        height=300
    )
    html_dd = fig_dd.to_html(full_html=False, include_plotlyjs=False)
    
    # 3. Annual Returns
    yearly_resampled = port_series.resample("YE").last()
    yearly_returns = yearly_resampled.pct_change().dropna()
    yearly_returns.index = yearly_returns.index.year
    
    fig_annual = go.Figure()
    fig_annual.add_trace(go.Bar(
        x=yearly_returns.index,
        y=yearly_returns,
        marker_color=["#00CC96" if x > 0 else "#EF553B" for x in yearly_returns],
        name="Annual Return"
    ))
    fig_annual.update_layout(
        title="Annual Returns",
        xaxis_title="Year",
        yaxis_title="Return",
        template="plotly_white",
        height=300
    )
    html_annual = fig_annual.to_html(full_html=False, include_plotlyjs=False)
    
    # Format Stats
    stats_html = "<div class='stats-grid'>"
    for k, v in stats.items():
        label = k.replace("_", " ").title()
        if isinstance(v, float):
            val_str = f"{v:.2f}"
            if "pct" in k.lower() or "cagr" in k.lower() or "drawdown" in k.lower() or "vol" in k.lower():
                val_str += "%"
        else:
            val_str = str(v)
        stats_html += f"<div class='stat-card'><div class='stat-label'>{label}</div><div class='stat-value'>{val_str}</div></div>"
    stats_html += "</div>"
    
    # Tax Table
    tax_html = ""
    if not pl_by_year.empty:
        tax_table = pl_by_year.copy()
        for col in tax_table.columns:
            if tax_table[col].dtype == float:
                tax_table[col] = tax_table[col].apply(lambda x: f"${x:,.2f}")
        tax_html = f"<h2>Tax Analysis</h2><div class='table-container'>{tax_table.to_html(classes='styled-table')}</div>"

    if show_title:
        html_out += "<h2>Performance Summary</h2>"
        
    html_out += f"""
    {stats_html}
    <div class="chart-container">{html_equity}</div>
    <div class="chart-container">{html_dd}</div>
    <div class="chart-container">{html_annual}</div>
    {tax_html}
    """
    
    return html_out

def _get_head_template():
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Testfol Backtest Report</title>
        <style>
            body {{ font-family: 'Helvetica', 'Arial', sans-serif; color: #333; line-height: 1.6; margin: 0; padding: 20px; background: #f4f4f9; }}
            .container {{ max_width: 1000px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-top: 40px; }}
            h2 {{ color: #34495e; margin-top: 30px; }}
            .section-divider {{ margin: 50px 0; border: 0; border-top: 2px solid #ccc; }}
            .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 15px; margin-bottom: 30px; }}
            .stat-card {{ background: #f8f9fa; padding: 15px; border-radius: 8px; border: 1px solid #eee; }}
            .stat-label {{ font-size: 0.85em; color: #7f8c8d; text-transform: uppercase; letter-spacing: 0.5px; }}
            .stat-value {{ font-size: 1.2em; font-weight: bold; color: #2c3e50; margin-top: 5px; }}
            .chart-container {{ margin-bottom: 40px; border: 1px solid #eee; padding: 10px; border-radius: 8px; }}
            .table-container {{ overflow-x: auto; }}
            .styled-table {{ width: 100%; border-collapse: collapse; margin: 25px 0; font-size: 0.9em; }}
            .styled-table thead tr {{ background-color: #009879; color: #ffffff; text-align: left; }}
            .styled-table th, .styled-table td {{ padding: 12px 15px; border-bottom: 1px solid #dddddd; }}
            .styled-table tbody tr:nth-of-type(even) {{ background-color: #f3f3f3; }}
            .styled-table tbody tr:last-of-type {{ border-bottom: 2px solid #009879; }}
            
            @media print {{
                body {{ background: white; padding: 0; }}
                .container {{ box-shadow: none; padding: 0; max-width: 100%; }}
                .chart-container {{ break-inside: avoid; }}
                h1, h2 {{ page-break-after: avoid; }}
                .page-break {{ page-break-before: always; }}
            }}
        </style>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    </head>
    """
